name: Scheduled DIP News

on:
  schedule:
    # Среда в 12:04 MSK → 9:04 UTC
    - cron: '04 9 * * Wed'
    # Пятница в 09:28 MSK → 6:28 UTC
    - cron: '28 6 * * Fri'
    # В остальные дни (понедельник, вторник, четверг, суббота, воскресенье) в 13:00 MSK → 10:00 UTC
    - cron: '03 10 * * Mon,Thu,Tue,Sat,Sun'
  workflow_dispatch: {}

jobs:
  run-dip-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run dip_news.py
        env:
          #GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          #PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          GOOGLE_TOKEN_B64: ${{ secrets.GOOGLE_TOKEN_B64 }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          FOLDERS_SANDBOX: ${{ secrets.FOLDERS_SANDBOX}}
          FOLDERS_MAIN: ${{ secrets.FOLDERS_MAIN}}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}
          PROXY: ${{ secrets.PROXY}}
        run: python dip_news.py
